### ISSUE TITLE
Slow startup when setup() called

### ISSUE THREAD

**Issue by JJGadgets** [diogo464/kubernetes.nvim#5]
Presumably due to the `setup()`'s `kubectl` command call, Neovim startup now takes a whole second.

Is it possible to have this run async so the `yamlls_schemas()` function won't cause the startup to be blocked for a second from the `setup()`?

![image](https://github.com/user-attachments/assets/fc2c3258-9fb0-47a4-a7ef-95b36377c5a7)

**Comment by diogo464** [comment]
The latest commit should fix the issue
